[package]
name = "rdf-query-cache"
version = "0.1.0"
edition = "2021"

[dependencies]
oxigraph = "0.3.6"
actix-web = "4.1.0"
lazy_static = "1.4.0"
prometheus = "0.13.2"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
thiserror = "1.0.31"
tracing = "0.1"
tracing-subscriber = "0.2"
moka = "0.9.4"
reqwest = "0.11.12"
mime = "0.3.16"
