[package]
name = "rdf-diff-store"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-rt = "2.7.0"
actix-web = "4.1.0"
async-lock = "2.5.0"
async-std = "1.12.0"
async-trait = "0.1.58"
base64 = "0.13.1"
futures-util = "0.3.25"
git2 = "0.16.1"
lazy_static = "1.4.0"
mime = "0.3.16"
moka = "0.9.4"
oxigraph = "0.3.6"
prometheus = "0.13.2"
reqwest = { version = "0.11.12", features = ["json"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
thiserror = "1.0.31"
tokio = { version = "1.21.2", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"
