openapi: 3.0.3
info:
  title: RDF Query Cache
  description: API for querying diff-store with cache
  version: 0.1.0

components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        error:
          type: string
    Graph:
      type: object
      properties:
        id:
          type: string
        format:
          type: string
        graph:
          type: string
      required:
        - id
        - graph
    Metadata:
      type: object
      properties:
        start_time:
          type: integer
          format: int64
        end_time:
          type: integer
          format: int64

paths:
  /api/graphs/{timestamp}:
    get:
      summary: Get graph at given timestamp.
      security:
        - apiKey: []
      parameters:
        - in: path
          name: timestamp
          required: true
          schema:
            title: Timestamp
            type: integer
        - in: query
          name: id
          required: false
          schema:
            title: Id
            type: string
      responses:
        "200":
          description: Ok
          content:
            text/turtle:
              schema:
                type: string
          headers: {}
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          headers: {}
  /api/graphs:
    post:
      summary: Store graph.
      security:
        - apiKey: []
      requestBody:
        description: Graph
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Graph"
      responses:
        "200":
          description: Ok
          content:
            text/turtle:
              schema:
                type: string
          headers: {}
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          headers: {}
    delete:
      summary: Delete graph.
      security:
        - apiKey: []
      parameters:
        - in: query
          name: id
          required: true
          schema:
            title: Id
            type: string
      responses:
        "200":
          description: Ok
          headers: {}
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          headers: {}
  /api/sparql/{timestamp}:
    get:
      summary: Query specific timestamp with SparQL.
      security:
        - apiKey: []
      parameters:
        - in: path
          name: timestamp
          required: true
          schema:
            title: Timestamp
            type: integer
        - in: query
          name: id
          required: false
          schema:
            title: Id
            type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
          headers: {}
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          headers: {}
