---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-rdf-diff-writer.yaml
  - deployment-rdf-query-cache.yaml
  - ingress.yaml
  - service-fdk-dataset-rdf-diff-writer.yaml
  - service-fdk-dataset-rdf-query-cache.yaml
