---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fdk-dataset-rdf-diff-writer
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
