/*
 * RDF Query Cache
 *
 * API for querying diff-store with cache
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Graph {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "format")]
    pub format: String,
    #[serde(rename = "graph")]
    pub graph: String,
}

impl Graph {
    pub fn new(id: String, format: String, graph: String) -> Graph {
        Graph {
            id,
            format,
            graph,
        }
    }
}


