name: Deploy to staging

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - main

jobs:
  test:
    name: Run tests when pull request is created
    if: github.event.pull_request.draft == false
    uses: Informasjonsforvaltning/workflows/.github/workflows/test-rust.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      cargo_args: -- --test-threads 1
      rust_env: |
        GIT_REPOS_ROOT_PATH=./tmp-repos
        GIT_REPO_URL=http://gitea:gitea123@localhost:3000/gitea/diff-store.git

  build-rdf-diff-writer:
    name: Build diff-writer when pull request is created
    if: github.event.pull_request.draft == false
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push.yaml@main
    with:
      app_name: rdf-diff-writer
      environment: staging
      build_env: true
      build_env_name: BINARY
      build_env_value: rdf-diff-writer
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GCP_SA_DIGDIR_FDK_GCR_KEY: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}

  build-rdf-query-cache:
    name: Build query-cache when pull request is created
    if: github.event.pull_request.draft == false
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push.yaml@main
    with:
      app_name: rdf-query-cache
      environment: staging
      build_env: true
      build_env_name: BINARY
      build_env_value: rdf-query-cache
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GCP_SA_DIGDIR_FDK_GCR_KEY: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}

  deploy:
    name: Deploy to staging environment with reusable workflow
    if: github.event.pull_request.draft == false
    needs: [test, build-rdf-diff-writer, build-rdf-query-cache]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@kustomize/at/short-sha
    with:
      app_name: rdf-query-cache
      image: eu.gcr.io/digdir-fdk-infra/rdf-query-cache:staging_latest
      environment: staging
      cluster: digdir-fdk-dev
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
