name: Deploy to production & demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run tests on merge to main
    if: github.event.pull_request.draft == false
    uses: Informasjonsforvaltning/workflows/.github/workflows/test-rust.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      cargo_args: -- --test-threads 1
      rust_env: |
        GIT_REPOS_ROOT_PATH=./tmp-repos/test
        GIT_REPO_BASE_URL=http://gitea:gitea123@localhost:3000
        GITEA_API_PATH=http://gitea:gitea123@localhost:3000/api

  build:
    name: Build diff-writer on merge to main
    needs: [test]
    strategy:
      matrix:
        app_name: [rdf-diff-writer, rdf-query-cache]
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push.yaml@main
    with:
      app_name: ${{ matrix.app_name }}
      environment: prod
      build_env: true
      build_env_name: BINARY
      build_env_value: ${{ matrix.app_name }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GCP_SA_DIGDIR_FDK_GCR_KEY: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}

  deploy:
    name: Deploy to prod environment
    if: github.event.pull_request.draft == false
    needs: [test, build]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: rdf-diff-store
      environment: prod
      cluster: digdir-fdk-prod
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy_demo:
    name: Deploy to demo environment
    if: github.event.pull_request.draft == false
    needs: [deploy]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: rdf-diff-store
      environment: demo
      cluster: digdir-fdk-dev
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
